---
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--required=false', '--args=--sort=false']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.9.0
    hooks:
      - id: talisman-commit
